/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TripRouteImport } from './routes/trip'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiRoamieRouteImport } from './routes/api/roamie'
import { Route as ApiGenerateItineraryRouteImport } from './routes/api/generate-itinerary'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSavedRouteImport } from './routes/_app.saved'
import { Route as AppRecommendationsRouteImport } from './routes/_app.recommendations'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlanRouteImport } from './routes/_app.plan'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppChatRouteImport } from './routes/_app.chat'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoamieRoute = ApiRoamieRouteImport.update({
  id: '/api/roamie',
  path: '/api/roamie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateItineraryRoute = ApiGenerateItineraryRouteImport.update({
  id: '/api/generate-itinerary',
  path: '/api/generate-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/intro': typeof IntroRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/splash': typeof SplashRoute
  '/trip': typeof TripRoute
  '/welcome': typeof WelcomeRoute
  '/chat': typeof AppChatRoute
  '/map': typeof AppMapRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/roamie': typeof ApiRoamieRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/intro': typeof IntroRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/splash': typeof SplashRoute
  '/trip': typeof TripRoute
  '/welcome': typeof WelcomeRoute
  '/chat': typeof AppChatRoute
  '/map': typeof AppMapRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/roamie': typeof ApiRoamieRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/intro': typeof IntroRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/splash': typeof SplashRoute
  '/trip': typeof TripRoute
  '/welcome': typeof WelcomeRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/map': typeof AppMapRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/roamie': typeof ApiRoamieRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intro'
    | '/loading'
    | '/login'
    | '/onboarding'
    | '/splash'
    | '/trip'
    | '/welcome'
    | '/chat'
    | '/map'
    | '/plan'
    | '/profile'
    | '/recommendations'
    | '/saved'
    | '/settings'
    | '/api/chat'
    | '/api/generate-itinerary'
    | '/api/roamie'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/intro'
    | '/loading'
    | '/login'
    | '/onboarding'
    | '/splash'
    | '/trip'
    | '/welcome'
    | '/chat'
    | '/map'
    | '/plan'
    | '/profile'
    | '/recommendations'
    | '/saved'
    | '/settings'
    | '/api/chat'
    | '/api/generate-itinerary'
    | '/api/roamie'
    | '/auth/callback'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/intro'
    | '/loading'
    | '/login'
    | '/onboarding'
    | '/splash'
    | '/trip'
    | '/welcome'
    | '/_app/chat'
    | '/_app/map'
    | '/_app/plan'
    | '/_app/profile'
    | '/_app/recommendations'
    | '/_app/saved'
    | '/_app/settings'
    | '/api/chat'
    | '/api/generate-itinerary'
    | '/api/roamie'
    | '/auth/callback'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  IntroRoute: typeof IntroRoute
  LoadingRoute: typeof LoadingRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SplashRoute: typeof SplashRoute
  TripRoute: typeof TripRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateItineraryRoute: typeof ApiGenerateItineraryRoute
  ApiRoamieRoute: typeof ApiRoamieRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roamie': {
      id: '/api/roamie'
      path: '/api/roamie'
      fullPath: '/api/roamie'
      preLoaderRoute: typeof ApiRoamieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-itinerary': {
      id: '/api/generate-itinerary'
      path: '/api/generate-itinerary'
      fullPath: '/api/generate-itinerary'
      preLoaderRoute: typeof ApiGenerateItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppMapRoute: typeof AppMapRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppMapRoute: AppMapRoute,
  AppPlanRoute: AppPlanRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppSavedRoute: AppSavedRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  IntroRoute: IntroRoute,
  LoadingRoute: LoadingRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SplashRoute: SplashRoute,
  TripRoute: TripRoute,
  WelcomeRoute: WelcomeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateItineraryRoute: ApiGenerateItineraryRoute,
  ApiRoamieRoute: ApiRoamieRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
