/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TripRouteImport } from './routes/trip'
import { Route as TravelPreferenceTestRouteImport } from './routes/travel-preference-test'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as TripInviteTokenRouteImport } from './routes/trip-invite.$token'
import { Route as LoginLegalRouteImport } from './routes/login/legal'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiRoamieRouteImport } from './routes/api/roamie'
import { Route as ApiPlacePhotoRouteImport } from './routes/api/place-photo'
import { Route as ApiGenerateItineraryRouteImport } from './routes/api/generate-itinerary'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppTravelDraftsRouteImport } from './routes/_app.travel-drafts'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSavedRouteImport } from './routes/_app.saved'
import { Route as AppRecommendationsRouteImport } from './routes/_app.recommendations'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlanRouteImport } from './routes/_app.plan'
import { Route as AppPlaceRouteImport } from './routes/_app.place'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppDeveloperRouteImport } from './routes/_app.developer'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppSavedIndexRouteImport } from './routes/_app.saved.index'
import { Route as ApiAnalyticsEventsRouteImport } from './routes/api/analytics/events'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as AppSavedTripIdRouteImport } from './routes/_app.saved.$tripId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelPreferenceTestRoute = TravelPreferenceTestRouteImport.update({
  id: '/travel-preference-test',
  path: '/travel-preference-test',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TripInviteTokenRoute = TripInviteTokenRouteImport.update({
  id: '/trip-invite/$token',
  path: '/trip-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLegalRoute = LoginLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => LoginRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoamieRoute = ApiRoamieRouteImport.update({
  id: '/api/roamie',
  path: '/api/roamie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacePhotoRoute = ApiPlacePhotoRouteImport.update({
  id: '/api/place-photo',
  path: '/api/place-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateItineraryRoute = ApiGenerateItineraryRouteImport.update({
  id: '/api/generate-itinerary',
  path: '/api/generate-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTravelDraftsRoute = AppTravelDraftsRouteImport.update({
  id: '/travel-drafts',
  path: '/travel-drafts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaceRoute = AppPlaceRouteImport.update({
  id: '/place',
  path: '/place',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperRoute = AppDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedIndexRoute = AppSavedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSavedRoute,
} as any)
const ApiAnalyticsEventsRoute = ApiAnalyticsEventsRouteImport.update({
  id: '/api/analytics/events',
  path: '/api/analytics/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSavedTripIdRoute = AppSavedTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => AppSavedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/travel-preference-test': typeof TravelPreferenceTestRoute
  '/trip': typeof TripRoute
  '/welcome': typeof WelcomeRoute
  '/chat': typeof AppChatRoute
  '/developer': typeof AppDeveloperRoute
  '/map': typeof AppMapRoute
  '/place': typeof AppPlaceRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/saved': typeof AppSavedRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/travel-drafts': typeof AppTravelDraftsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/api/roamie': typeof ApiRoamieRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/legal': typeof LoginLegalRoute
  '/trip-invite/$token': typeof TripInviteTokenRoute
  '/saved/$tripId': typeof AppSavedTripIdRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/analytics/events': typeof ApiAnalyticsEventsRoute
  '/saved/': typeof AppSavedIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/travel-preference-test': typeof TravelPreferenceTestRoute
  '/trip': typeof TripRoute
  '/welcome': typeof WelcomeRoute
  '/chat': typeof AppChatRoute
  '/developer': typeof AppDeveloperRoute
  '/map': typeof AppMapRoute
  '/place': typeof AppPlaceRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/settings': typeof AppSettingsRoute
  '/travel-drafts': typeof AppTravelDraftsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/api/roamie': typeof ApiRoamieRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/legal': typeof LoginLegalRoute
  '/trip-invite/$token': typeof TripInviteTokenRoute
  '/': typeof AppIndexRoute
  '/saved/$tripId': typeof AppSavedTripIdRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/analytics/events': typeof ApiAnalyticsEventsRoute
  '/saved': typeof AppSavedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/travel-preference-test': typeof TravelPreferenceTestRoute
  '/trip': typeof TripRoute
  '/welcome': typeof WelcomeRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/developer': typeof AppDeveloperRoute
  '/_app/map': typeof AppMapRoute
  '/_app/place': typeof AppPlaceRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/saved': typeof AppSavedRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/travel-drafts': typeof AppTravelDraftsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/api/roamie': typeof ApiRoamieRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/legal': typeof LoginLegalRoute
  '/trip-invite/$token': typeof TripInviteTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/saved/$tripId': typeof AppSavedTripIdRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/analytics/events': typeof ApiAnalyticsEventsRoute
  '/_app/saved/': typeof AppSavedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/travel-preference-test'
    | '/trip'
    | '/welcome'
    | '/chat'
    | '/developer'
    | '/map'
    | '/place'
    | '/plan'
    | '/profile'
    | '/recommendations'
    | '/saved'
    | '/settings'
    | '/travel-drafts'
    | '/api/chat'
    | '/api/generate-itinerary'
    | '/api/place-photo'
    | '/api/roamie'
    | '/auth/callback'
    | '/login/legal'
    | '/trip-invite/$token'
    | '/saved/$tripId'
    | '/api/admin/dashboard'
    | '/api/analytics/events'
    | '/saved/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/travel-preference-test'
    | '/trip'
    | '/welcome'
    | '/chat'
    | '/developer'
    | '/map'
    | '/place'
    | '/plan'
    | '/profile'
    | '/recommendations'
    | '/settings'
    | '/travel-drafts'
    | '/api/chat'
    | '/api/generate-itinerary'
    | '/api/place-photo'
    | '/api/roamie'
    | '/auth/callback'
    | '/login/legal'
    | '/trip-invite/$token'
    | '/'
    | '/saved/$tripId'
    | '/api/admin/dashboard'
    | '/api/analytics/events'
    | '/saved'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/travel-preference-test'
    | '/trip'
    | '/welcome'
    | '/_app/chat'
    | '/_app/developer'
    | '/_app/map'
    | '/_app/place'
    | '/_app/plan'
    | '/_app/profile'
    | '/_app/recommendations'
    | '/_app/saved'
    | '/_app/settings'
    | '/_app/travel-drafts'
    | '/api/chat'
    | '/api/generate-itinerary'
    | '/api/place-photo'
    | '/api/roamie'
    | '/auth/callback'
    | '/login/legal'
    | '/trip-invite/$token'
    | '/_app/'
    | '/_app/saved/$tripId'
    | '/api/admin/dashboard'
    | '/api/analytics/events'
    | '/_app/saved/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  TravelPreferenceTestRoute: typeof TravelPreferenceTestRoute
  TripRoute: typeof TripRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateItineraryRoute: typeof ApiGenerateItineraryRoute
  ApiPlacePhotoRoute: typeof ApiPlacePhotoRoute
  ApiRoamieRoute: typeof ApiRoamieRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  TripInviteTokenRoute: typeof TripInviteTokenRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAnalyticsEventsRoute: typeof ApiAnalyticsEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-preference-test': {
      id: '/travel-preference-test'
      path: '/travel-preference-test'
      fullPath: '/travel-preference-test'
      preLoaderRoute: typeof TravelPreferenceTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/trip-invite/$token': {
      id: '/trip-invite/$token'
      path: '/trip-invite/$token'
      fullPath: '/trip-invite/$token'
      preLoaderRoute: typeof TripInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/legal': {
      id: '/login/legal'
      path: '/legal'
      fullPath: '/login/legal'
      preLoaderRoute: typeof LoginLegalRouteImport
      parentRoute: typeof LoginRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roamie': {
      id: '/api/roamie'
      path: '/api/roamie'
      fullPath: '/api/roamie'
      preLoaderRoute: typeof ApiRoamieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/place-photo': {
      id: '/api/place-photo'
      path: '/api/place-photo'
      fullPath: '/api/place-photo'
      preLoaderRoute: typeof ApiPlacePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-itinerary': {
      id: '/api/generate-itinerary'
      path: '/api/generate-itinerary'
      fullPath: '/api/generate-itinerary'
      preLoaderRoute: typeof ApiGenerateItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/travel-drafts': {
      id: '/_app/travel-drafts'
      path: '/travel-drafts'
      fullPath: '/travel-drafts'
      preLoaderRoute: typeof AppTravelDraftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/place': {
      id: '/_app/place'
      path: '/place'
      fullPath: '/place'
      preLoaderRoute: typeof AppPlaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer': {
      id: '/_app/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AppDeveloperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved/': {
      id: '/_app/saved/'
      path: '/'
      fullPath: '/saved/'
      preLoaderRoute: typeof AppSavedIndexRouteImport
      parentRoute: typeof AppSavedRoute
    }
    '/api/analytics/events': {
      id: '/api/analytics/events'
      path: '/api/analytics/events'
      fullPath: '/api/analytics/events'
      preLoaderRoute: typeof ApiAnalyticsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/saved/$tripId': {
      id: '/_app/saved/$tripId'
      path: '/$tripId'
      fullPath: '/saved/$tripId'
      preLoaderRoute: typeof AppSavedTripIdRouteImport
      parentRoute: typeof AppSavedRoute
    }
  }
}

interface AppSavedRouteChildren {
  AppSavedTripIdRoute: typeof AppSavedTripIdRoute
  AppSavedIndexRoute: typeof AppSavedIndexRoute
}

const AppSavedRouteChildren: AppSavedRouteChildren = {
  AppSavedTripIdRoute: AppSavedTripIdRoute,
  AppSavedIndexRoute: AppSavedIndexRoute,
}

const AppSavedRouteWithChildren = AppSavedRoute._addFileChildren(
  AppSavedRouteChildren,
)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDeveloperRoute: typeof AppDeveloperRoute
  AppMapRoute: typeof AppMapRoute
  AppPlaceRoute: typeof AppPlaceRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppSavedRoute: typeof AppSavedRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTravelDraftsRoute: typeof AppTravelDraftsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDeveloperRoute: AppDeveloperRoute,
  AppMapRoute: AppMapRoute,
  AppPlaceRoute: AppPlaceRoute,
  AppPlanRoute: AppPlanRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppSavedRoute: AppSavedRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTravelDraftsRoute: AppTravelDraftsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LoginRouteChildren {
  LoginLegalRoute: typeof LoginLegalRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginLegalRoute: LoginLegalRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  TravelPreferenceTestRoute: TravelPreferenceTestRoute,
  TripRoute: TripRoute,
  WelcomeRoute: WelcomeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateItineraryRoute: ApiGenerateItineraryRoute,
  ApiPlacePhotoRoute: ApiPlacePhotoRoute,
  ApiRoamieRoute: ApiRoamieRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  TripInviteTokenRoute: TripInviteTokenRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAnalyticsEventsRoute: ApiAnalyticsEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
