/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TripRouteImport } from './routes/trip'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as LoginLegalRouteImport } from './routes/login/legal'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiRoamieRouteImport } from './routes/api/roamie'
import { Route as ApiPlacePhotoRouteImport } from './routes/api/place-photo'
import { Route as ApiGenerateItineraryRouteImport } from './routes/api/generate-itinerary'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSavedRouteImport } from './routes/_app.saved'
import { Route as AppRecommendationsRouteImport } from './routes/_app.recommendations'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlanRouteImport } from './routes/_app.plan'
import { Route as AppPlaceRouteImport } from './routes/_app.place'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppDeveloperRouteImport } from './routes/_app.developer'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppSavedTripIdRouteImport } from './routes/_app.saved.$tripId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LoginLegalRoute = LoginLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => LoginRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoamieRoute = ApiRoamieRouteImport.update({
  id: '/api/roamie',
  path: '/api/roamie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacePhotoRoute = ApiPlacePhotoRouteImport.update({
  id: '/api/place-photo',
  path: '/api/place-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateItineraryRoute = ApiGenerateItineraryRouteImport.update({
  id: '/api/generate-itinerary',
  path: '/api/generate-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaceRoute = AppPlaceRouteImport.update({
  id: '/place',
  path: '/place',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperRoute = AppDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedTripIdRoute = AppSavedTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => AppSavedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/trip': typeof TripRoute
  '/welcome': typeof WelcomeRoute
  '/chat': typeof AppChatRoute
  '/developer': typeof AppDeveloperRoute
  '/map': typeof AppMapRoute
  '/place': typeof AppPlaceRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/saved': typeof AppSavedRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/api/roamie': typeof ApiRoamieRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/legal': typeof LoginLegalRoute
  '/saved/$tripId': typeof AppSavedTripIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteWithChildren
  '/trip': typeof TripRoute
  '/welcome': typeof WelcomeRoute
  '/chat': typeof AppChatRoute
  '/developer': typeof AppDeveloperRoute
  '/map': typeof AppMapRoute
  '/place': typeof AppPlaceRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/saved': typeof AppSavedRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/api/roamie': typeof ApiRoamieRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/legal': typeof LoginLegalRoute
  '/': typeof AppIndexRoute
  '/saved/$tripId': typeof AppSavedTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/trip': typeof TripRoute
  '/welcome': typeof WelcomeRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/developer': typeof AppDeveloperRoute
  '/_app/map': typeof AppMapRoute
  '/_app/place': typeof AppPlaceRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/saved': typeof AppSavedRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-itinerary': typeof ApiGenerateItineraryRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/api/roamie': typeof ApiRoamieRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/legal': typeof LoginLegalRoute
  '/_app/': typeof AppIndexRoute
  '/_app/saved/$tripId': typeof AppSavedTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/trip'
    | '/welcome'
    | '/chat'
    | '/developer'
    | '/map'
    | '/place'
    | '/plan'
    | '/profile'
    | '/recommendations'
    | '/saved'
    | '/settings'
    | '/api/chat'
    | '/api/generate-itinerary'
    | '/api/place-photo'
    | '/api/roamie'
    | '/auth/callback'
    | '/login/legal'
    | '/saved/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/trip'
    | '/welcome'
    | '/chat'
    | '/developer'
    | '/map'
    | '/place'
    | '/plan'
    | '/profile'
    | '/recommendations'
    | '/saved'
    | '/settings'
    | '/api/chat'
    | '/api/generate-itinerary'
    | '/api/place-photo'
    | '/api/roamie'
    | '/auth/callback'
    | '/login/legal'
    | '/'
    | '/saved/$tripId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/trip'
    | '/welcome'
    | '/_app/chat'
    | '/_app/developer'
    | '/_app/map'
    | '/_app/place'
    | '/_app/plan'
    | '/_app/profile'
    | '/_app/recommendations'
    | '/_app/saved'
    | '/_app/settings'
    | '/api/chat'
    | '/api/generate-itinerary'
    | '/api/place-photo'
    | '/api/roamie'
    | '/auth/callback'
    | '/login/legal'
    | '/_app/'
    | '/_app/saved/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  TripRoute: typeof TripRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateItineraryRoute: typeof ApiGenerateItineraryRoute
  ApiPlacePhotoRoute: typeof ApiPlacePhotoRoute
  ApiRoamieRoute: typeof ApiRoamieRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/login/legal': {
      id: '/login/legal'
      path: '/legal'
      fullPath: '/login/legal'
      preLoaderRoute: typeof LoginLegalRouteImport
      parentRoute: typeof LoginRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roamie': {
      id: '/api/roamie'
      path: '/api/roamie'
      fullPath: '/api/roamie'
      preLoaderRoute: typeof ApiRoamieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/place-photo': {
      id: '/api/place-photo'
      path: '/api/place-photo'
      fullPath: '/api/place-photo'
      preLoaderRoute: typeof ApiPlacePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-itinerary': {
      id: '/api/generate-itinerary'
      path: '/api/generate-itinerary'
      fullPath: '/api/generate-itinerary'
      preLoaderRoute: typeof ApiGenerateItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/place': {
      id: '/_app/place'
      path: '/place'
      fullPath: '/place'
      preLoaderRoute: typeof AppPlaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer': {
      id: '/_app/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AppDeveloperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved/$tripId': {
      id: '/_app/saved/$tripId'
      path: '/$tripId'
      fullPath: '/saved/$tripId'
      preLoaderRoute: typeof AppSavedTripIdRouteImport
      parentRoute: typeof AppSavedRoute
    }
  }
}

interface AppSavedRouteChildren {
  AppSavedTripIdRoute: typeof AppSavedTripIdRoute
}

const AppSavedRouteChildren: AppSavedRouteChildren = {
  AppSavedTripIdRoute: AppSavedTripIdRoute,
}

const AppSavedRouteWithChildren = AppSavedRoute._addFileChildren(
  AppSavedRouteChildren,
)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDeveloperRoute: typeof AppDeveloperRoute
  AppMapRoute: typeof AppMapRoute
  AppPlaceRoute: typeof AppPlaceRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppSavedRoute: typeof AppSavedRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDeveloperRoute: AppDeveloperRoute,
  AppMapRoute: AppMapRoute,
  AppPlaceRoute: AppPlaceRoute,
  AppPlanRoute: AppPlanRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppSavedRoute: AppSavedRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LoginRouteChildren {
  LoginLegalRoute: typeof LoginLegalRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginLegalRoute: LoginLegalRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  TripRoute: TripRoute,
  WelcomeRoute: WelcomeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateItineraryRoute: ApiGenerateItineraryRoute,
  ApiPlacePhotoRoute: ApiPlacePhotoRoute,
  ApiRoamieRoute: ApiRoamieRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
