// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function normalizeSupabaseUrl(url: string): string {
  // Some environments accidentally set VITE_SUPABASE_URL to .../rest/v1 or .../auth/v1.
  // Supabase client expects the project base origin (https://<ref>.supabase.co).
  return url.replace(/\/(rest|auth)\/v1\/?$/i, "").replace(/\/$/, "");
}

function readSupabaseEnv(): { url?: string; key?: string } {
  const rawUrl = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const key =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;
  return {
    url: rawUrl ? normalizeSupabaseUrl(rawUrl) : undefined,
    key: typeof key === "string" && key.length > 0 ? key : undefined,
  };
}

/** Build-time / runtime：Supabase 是否已設定（TestFlight 需在 build 時帶入 VITE_*） */
export function isSupabaseConfigured(): boolean {
  const { url, key } = readSupabaseEnv();
  return Boolean(url && key);
}

let configWarningLogged = false;
let clientInstance: SupabaseClient<Database> | null = null;

function logMissingConfigOnce(): void {
  if (configWarningLogged) return;
  configWarningLogged = true;
  const { url, key } = readSupabaseEnv();
  const missing = [
    ...(!url ? ["VITE_SUPABASE_URL"] : []),
    ...(!key ? ["VITE_SUPABASE_PUBLISHABLE_KEY"] : []),
  ];
  console.error(
    `[Supabase] Missing environment variable(s): ${missing.join(", ")}. ` +
      "App will not be able to sign in. Rebuild with .env for TestFlight.",
  );
}

function createSupabaseClient(): SupabaseClient<Database> {
  const { url, key } = readSupabaseEnv();

  if (!url || !key) {
    logMissingConfigOnce();
    // 不 throw：避免 Capacitor 冷啟動整包 JS 在 import 階段就崩潰
    return createClient<Database>(
      "https://placeholder.supabase.co",
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSJ9.missing-build-env",
      {
        auth: {
          storage: typeof window !== "undefined" ? window.localStorage : undefined,
          storageKey: "roamie-auth",
          persistSession: typeof window !== "undefined",
          autoRefreshToken: false,
          detectSessionInUrl: false,
          flowType: "pkce",
        },
      },
    );
  }

  return createClient<Database>(url, key, {
    auth: {
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
      storageKey: "roamie-auth",
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
      flowType: "pkce",
    },
  });
}

/** 全專案唯一瀏覽器 Supabase client（延遲建立，import 時不 throw） */
export function getSupabaseClient(): SupabaseClient<Database> {
  clientInstance ??= createSupabaseClient();
  return clientInstance;
}

/** @deprecated 請用 getSupabaseClient；保留相容與 Proxy 轉發 */
export const supabase: SupabaseClient<Database> = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop) {
    const client = getSupabaseClient();
    const value = Reflect.get(client, prop, client);
    if (typeof value === "function") {
      return (value as (...args: unknown[]) => unknown).bind(client);
    }
    return value;
  },
});
