// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { createSupabaseAuthStorage } from "@/lib/supabase-auth-storage";
import { createCapacitorSupabaseFetch } from "@/lib/native-capacitor-http";
import {
  getSupabaseEnvCheckSnapshot,
  isSupabaseViteEnvValid,
  logSupabaseEnvCheck,
  normalizeSupabaseProjectUrl,
} from "@/lib/vite-supabase-env";
import type { Database } from "./types";

const supabaseGlobalFetch = createCapacitorSupabaseFetch();

function readViteEnvString(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  if (!trimmed || trimmed === "undefined") return undefined;
  return trimmed;
}

/** 僅讀 import.meta.env.VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY */
function readSupabaseEnv(): { url?: string; key?: string } {
  const rawUrl = readViteEnvString(import.meta.env.VITE_SUPABASE_URL);
  const rawKey = readViteEnvString(import.meta.env.VITE_SUPABASE_ANON_KEY);
  return {
    url: rawUrl ? normalizeSupabaseProjectUrl(rawUrl) : undefined,
    key: rawKey,
  };
}

export function isSupabaseConfigured(): boolean {
  return isSupabaseViteEnvValid();
}

export { logSupabaseEnvCheck, getSupabaseEnvCheckSnapshot };

let configWarningLogged = false;
let clientInstance: SupabaseClient<Database> | null = null;

function logMissingConfigOnce(): void {
  if (configWarningLogged) return;
  configWarningLogged = true;
  const { url, key } = readSupabaseEnv();
  const missing = [
    ...(!url ? ["VITE_SUPABASE_URL"] : []),
    ...(!key ? ["VITE_SUPABASE_ANON_KEY"] : []),
  ];
  console.error(
    `[Supabase] Missing environment variable(s): ${missing.join(", ")}. ` +
      "Rebuild with .env (Dashboard → API → anon public key) then npm run cap:sync:ios.",
  );
}

function createSupabaseClient(): SupabaseClient<Database> {
  const { url, key } = readSupabaseEnv();
  const authStorage = createSupabaseAuthStorage();

  if (!url || !key) {
    logMissingConfigOnce();
    return createClient<Database>(
      "https://placeholder.supabase.co",
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSJ9.missing-build-env",
      {
        global: { fetch: supabaseGlobalFetch },
        auth: {
          storage: authStorage,
          storageKey: "roamie-auth",
          persistSession: Boolean(authStorage),
          autoRefreshToken: false,
          detectSessionInUrl: false,
          flowType: "pkce",
        },
      },
    );
  }

  return createClient<Database>(url, key, {
    global: { fetch: supabaseGlobalFetch },
    auth: {
      storage: authStorage,
      storageKey: "roamie-auth",
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
      flowType: "pkce",
    },
  });
}

export function getSupabaseClient(): SupabaseClient<Database> {
  clientInstance ??= createSupabaseClient();
  return clientInstance;
}

export const supabase: SupabaseClient<Database> = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop) {
    const client = getSupabaseClient();
    const value = Reflect.get(client, prop, client);
    if (typeof value === "function") {
      return (value as (...args: unknown[]) => unknown).bind(client);
    }
    return value;
  },
});
