require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!
MIN_IOS_DEPLOYMENT_TARGET = '15.0'

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAppleSignIn', :path => '../../node_modules/@capacitor-community/apple-sign-in'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorClipboard', :path => '../../node_modules/@capacitor/clipboard'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

def mark_cp_script_phases_always_run(project)
  project.targets.each do |target|
    target.shell_script_build_phases.each do |phase|
      name = phase.name.to_s
      next unless name.include?('[CP]') || name.include?('XCFrameworks')
      phase.always_out_of_date = '1'
    end
  end
end

def suppress_third_party_build_noise(installer)
  suppress_objc_synthesis = ['CapacitorKeyboard']
  suppress_deprecated = ['Capacitor', 'CapacitorCordova']

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if suppress_objc_synthesis.include?(target.name)
        config.build_settings['CLANG_WARN_OBJC_PROTOCOL_PROPERTY_SYNTHESIS'] = 'NO'
        config.build_settings['WARNING_CFLAGS'] ||= ['$(inherited)']
        config.build_settings['WARNING_CFLAGS'] << '-Wno-objc-protocol-property-synthesis' unless config.build_settings['WARNING_CFLAGS'].include?('-Wno-objc-protocol-property-synthesis')
      end
      if suppress_deprecated.include?(target.name)
        config.build_settings['GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS'] = 'NO'
        config.build_settings['CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS'] = 'NO'
        other_swift = config.build_settings['OTHER_SWIFT_FLAGS'] || '$(inherited)'
        config.build_settings['OTHER_SWIFT_FLAGS'] = "#{other_swift} -suppress-warnings"
      end
    end
  end

  mark_cp_script_phases_always_run(installer.pods_project)
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        # Cordova CDVWebViewProcessPoolFactory.h deprecations when imported by App target.
        config.build_settings['WARNING_CFLAGS'] ||= ['$(inherited)']
        flags = config.build_settings['WARNING_CFLAGS']
        flags << '-Wno-deprecated-declarations' unless flags.include?('-Wno-deprecated-declarations')
      end
    end
    mark_cp_script_phases_always_run(aggregate_target.user_project)
  end
end

def enforce_ios_deployment_target(installer, version)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = version
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = version
      end
    end
  end
end

post_install do |installer|
  assertDeploymentTarget(installer)
  enforce_ios_deployment_target(installer, MIN_IOS_DEPLOYMENT_TARGET)
  suppress_third_party_build_noise(installer)
end
